# Generated by Django 2.2 on 2020-12-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verkkomedia_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='verkkomedia_api.News')),
                ('name', models.CharField(max_length=500)),
                ('image', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
    ]
