# Generated by Django 2.2 on 2020-12-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkkomedia_api', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
