# Generated by Django 2.2 on 2020-12-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verkkomedia_api', '0004_auto_20201203_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='/', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=1000)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verkkomedia_api.News')),
            ],
        ),
    ]
