# Generated by Django 2.2 on 2020-12-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkkomedia_api', '0005_auto_20201210_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='news',
            new_name='news_parent',
        ),
        migrations.AddField(
            model_name='review',
            name='news_id',
            field=models.IntegerField(default=0),
        ),
    ]
